### PR TITLE
Making the website easier to navigate

### PR DESCRIPTION
**Pull request by jjouifi**
Hello,

I like Sozi a lot, but I find the website a little difficult to get around.
I've made some modifications to its organization -not modifying content- that make it clearer in my opinion.

If you like the mods I suggest, I can rewrite the "About" page later on, which I think should be expanded with more information.
I also think the 'about' page should be the front page of the site, because a visitor who wants to know about Sozi is looking for a short description, not a list of releases. But I didn't find the way to change this ;)

Talk to you,
JJ

### CODE REVIEW

**Comment by senshu** [comment]
Thanks for your contribution.
Before I go check the code, could you please give me a little summary of the changes that you did?

**Comment by jjouifi** [comment]
Hello,

Sure. If you look at my proposal in a browser, you'll see right away what I mean.

I've rearranged menus and content slightly to make the website a little easier to navigate for a new user, taking good care not to modify the content too much.

- Added a link to the Install page on the top bar (the user needs to find it quickly)
- Reorganised the Install page (it was difficult to understand where to find the install images for Linux)
- Added a link to the demo repository that you created recently, which did not appear on the website.
- ..


I haven't modified the templates or the config files at all, just the pages.

Good luck :)
JJ

**Comment by jjouifi** [comment]
Hello,

I've just added stuff to the 'About' page (EN only). More info about Sozi..
Let me know if you like it, I'll translate to French.

Bon w.e.,
JJ

**Comment by jjouifi** [comment]
News ?

Cheers,

**Comment by senshu** [comment]
I have merged your changes into a separate branch.
I will make a few changes before publishing the new version.

By the way, it seems that `{:target=_blank}` has no effect.

**Comment by jjouifi** [comment]
Cool. Let me know if you wish more content.

{:target=_blank} does work in my setup, opening the link in a new page... weird.
I'm using pelican 4.2.0 in Ubuntu 18.04.. 

cheers

**Comment by senshu** [comment]
> By the way, it seems that {:target=_blank} has no effect.

Sorry. It was my mistake.

The new version is now merged into master and published.
I have removed a few things that were no longer useful and rephrased some parts.
The home page is still the list of releases: this behavior is hard-coded in the templates of the site.

**Pull request merged**
