### PR TITLE
170118 Added German translations of the 5 first-level pages

### PR DESCRIPTION
**Pull request by Draussenduscher**
Please add these 5 German translations. I'll do the next pages concerning version 15/16 soon.
Thanks
Andrej

### CODE REVIEW

**Comment by senshu** [comment]
Thanks. I have fixed the language in `contribute.md`. The `Lang` attribute was still set to `en`.

**Comment by Draussenduscher** [comment]
Thank you for your quick reply Guillaume,

1st I want to thank you for this nice piece of software. I have used it
for a presentation in our beekeepers association last Tuesday, it is
magnificent! Just, what I needed!

2nd I will add more German translations for the pages concerning the
current version these days.

3rd I want to support you with updating online help. I understand you
don't want to spend too much time here. I suggest you just send me a
list of the definitive features to be described. I think I can create
the English (and German) text + screenshots. After you have checked it,
you can provide it at the web site. What do you think?

Best regards

Andrej
aka Draussenduscher


Am 19.01.17 um 21:33Uhr schrieb Guillaume Savaton:

**Comment by Draussenduscher** [comment]
Dear Guillaume,

some links are broken in the new, German pages. They have |filename| in
the middle!?

It's probably a thing you can easily fix, can't you?

Best regards

Andrej

Am 19.01.17 um 21:33Uhr schrieb Guillaume Savaton:

**Comment by senshu** [comment]
> I want to support you with updating online help. I understand you don't want to spend too much time here. I suggest you just send me a list of the definitive features to be described.

In fact, I have very little time to spend on Sozi (software as well as documentation) at the moment, so I would really appreciate some help.
I think that you could start by updating [the page on layers](http://sozi.baierouge.fr/pages/tutorial-layers.html).

> some links are broken in the new, German pages. They have |filename| in the middle!?

These are links to pages that are not available yet in your language. There is no automatic redirection to the English version.
A workaround would be to create stub pages with "not translated yet" in the body.

**Pull request merged**
