### PR TITLE
pt_br Release pages updated

### PR DESCRIPTION
**Pull request by guripreto**
two pages translated today.

### CODE REVIEW

**Comment by senshu** [comment]
Thanks for your contribution, but I cannot merge this pull request because of conflicting files. Did you pull from my repository before making your changes?

* Files `release-17.06.md` and `release-17.11.md` should contain the English version of the release notes. Please create new files with your translations as `release-17.06-pt_br.md` and `release-17.11-pt_br.md`.
* It seems that you created the file `content/pages/pt_br/donate.md` instead of editing the existing one.

**Comment by guripreto** [comment]
Hi Guillaume,
Hope I solved the conflict this time.
About the donate page, I did the translation directly, is it right?
tx

**Comment by senshu** [comment]
> Hope I solved the conflict this time.

It's OK. Github still detected a conflict with `donate.md` but it was easy to fix.

> About the donate page, I did the translation directly, is it right?

Yes.

I've added a non-translated donation page to every language section of the site to prevent broken links.
Translators are supposed to replace the English text with the translation.

**Comment by guripreto** [comment]
tx!!!

**Pull request merged**
